oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    auth-uri: "https://kauth.kakao.com/oauth/authorize"
    redirect-uri: "http://localhost:3000/oauth/callback/kakao"
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"
    scope: "profile_nickname,profile_image,account_email"
