spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: test1234!!
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petglam?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wlgh7078!!

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

security:
  jwt:
    secret: "your-secret-key-should-be-at-least-256-bits-long-for-security-reasons"
    access-token-expiration: PT1H  # 1 hour
    refresh-token-expiration: P30D  # 30 days
    issuer: "petglam-api"

oauth2:
  kakao:
    client-id: ${OAUTH2_KAKAO_CLIENT_ID}
    client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
    redirect-uri: "http://localhost:8080/api/v1/oauth2/callback/kakao"
    auth-uri: "https://kauth.kakao.com/oauth/authorize"
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"
    scopes: "profile_nickname,profile_image,account_email"

app:
  version:
    fail-safe-min-version: "1.0.0"
    redis-key-prefix: "app_version:min_supported:"

logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.messaging: TRACE
    com.copago.petglam.chat: DEBUG # 현재 프로젝트의 채팅 관련 패키지