spring:
  datasource:
    url: jdbc:h2:mem:petglam
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    secret: "your-secret-key-should-be-at-least-256-bits-long-for-security-reasons"
    access-token-expiration: PT1H  # 1 hour
    refresh-token-expiration: P30D  # 30 days
    issuer: "petglam-api"

oauth2:
  kakao:
    client-id: ${OAUTH2_KAKAO_CLIENT_ID}
    client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
    redirect-uri: "http://localhost:8080/api/v1/oauth2/callback/kakao"
    auth-uri: "https://kauth.kakao.com/oauth/authorize"
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"
    scopes: "profile_nickname,profile_image,account_email"
